CREATE TABLE "BASEDETAIL" ("RULEID" NUMBER(18) NOT NULL, 
    "CZFPBM" VARCHAR2(20 byte) NOT NULL, "BNUM" NUMBER(16, 2) NOT
    NULL, 
    CONSTRAINT "PK_BASEDETAIL" PRIMARY KEY("RULEID", "CZFPBM") 
    USING INDEX  
);
CREATE TABLE "BG_INFO" ("XH" NUMBER(18) NOT NULL, "SWDJZH" 
    VARCHAR2(20 byte) NOT NULL, "C_FIELD" VARCHAR2(50 byte) NOT 
    NULL, "SOURCE" NUMBER(1) DEFAULT 0 NOT NULL, "F_INIT" 
    VARCHAR2(100 byte) DEFAULT 0, "F_DEST" VARCHAR2(100 byte) 
    DEFAULT 0, "T_INIT" VARCHAR2(100 byte) DEFAULT 0, "T_DEST" 
    VARCHAR2(100 byte) DEFAULT 0, "BGRQ" NUMBER(8) DEFAULT 0 NOT 
    NULL, "FLAG" VARCHAR2(1 byte) DEFAULT '1', 
    CONSTRAINT "PK_BGINFO" PRIMARY KEY("XH", "C_FIELD", "SOURCE",
    "BGRQ") 
    USING INDEX  
);
CREATE TABLE "BM" ("NAME" VARCHAR2(50 byte) NOT NULL,
    "T_BM" VARCHAR2(20 byte) NOT NULL, "WHO" NUMBER(1) DEFAULT 0
    NOT NULL, "F_BM" VARCHAR2(10 byte) NOT NULL, "T_MC" VARCHAR2(50 byte) NOT NULL,
    CONSTRAINT "P_BM" PRIMARY KEY("NAME", "T_BM", "WHO", "F_BM")
    USING INDEX
);

CREATE TABLE "BM_CONT" ("TABLE_BM" VARCHAR2(40 byte) NOT
    NULL, "BM" VARCHAR2(42 byte) NOT NULL, "MC" VARCHAR2(200
    byte) NOT NULL, "PID" VARCHAR2(42 byte) DEFAULT '', "QYBJ"
    NUMBER(1) DEFAULT 1, "ISLEAF" NUMBER(1) DEFAULT 1,
    "CODELEVEL" NUMBER(2) DEFAULT 3,
    CONSTRAINT "PK_BM_CONT" PRIMARY KEY("TABLE_BM","BM")
    USING INDEX
);
CREATE TABLE "BM_CONT_TAX" ("TABLE_BM" VARCHAR2(40 byte)
    NOT NULL, "BM" VARCHAR2(40 byte) NOT NULL, "MC" VARCHAR2(100
    byte) NOT NULL, "PID" VARCHAR2(40 byte) DEFAULT '', "QYBJ"
    NUMBER(1) DEFAULT 1, "ISLEAF" NUMBER(1) DEFAULT 1 NOT NULL,
    "CODELEVEL" NUMBER(2) DEFAULT 3 NOT NULL, "WHO" NUMBER(1)
    DEFAULT 0 NOT NULL, "STATUS" NUMBER(1) DEFAULT 0,
    CONSTRAINT "PK_BM_CONT_TAX" PRIMARY KEY("TABLE_BM", "BM")
    USING INDEX
);
CREATE TABLE "BM_INDEX" (
	"TABLE_BM" VARCHAR2(40 byte) NOT NULL,
    "NAME" VARCHAR2(100 byte) NOT NULL, "QYBJ" NUMBER(1) DEFAULT 1,
    "REMARK" VARCHAR2(1000 byte),
    CONSTRAINT "PK_BM_INDEX" PRIMARY KEY("TABLE_BM")
    USING INDEX
);
CREATE TABLE "BM_INDEX_TAX" (
	"TABLE_BM" VARCHAR2(40 byte) NOT NULL,
    "NAME" VARCHAR2(100 byte) NOT NULL, "QYBJ" NUMBER(1) DEFAULT 1,"WHO" NUMBER(1),
    "REMARK" VARCHAR2(1000 byte),
    CONSTRAINT "PK_BM_INDEX_TAX" PRIMARY KEY("TABLE_BM")
    USING INDEX
);
CREATE TABLE "BM_TABLE_MAP" ("F_TABLE" VARCHAR2(50 byte)
    NOT NULL, "T_TABLE" VARCHAR2(50 byte) NOT NULL, "WHO"
    NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_BM_TABLE_MAP" UNIQUE("F_TABLE", "T_TABLE")
    USING INDEX
);
CREATE TABLE "CHECKTASK" ("ID" NUMBER(18) NOT NULL, "ENID"
    VARCHAR2(20 byte) NOT NULL, "FLDNAME" VARCHAR2(30 byte) NOT NULL, 
    "NEWVAL" VARCHAR2(200 byte) NOT NULL, "OLDVAL" VARCHAR2(200 byte),
    "YXRTK" NUMBER(1),"FROMDAY" NUMBER(8), "TODAY" NUMBER(8), "YXTYPE" NUMBER(1), 
    "CJUSER" VARCHAR2(50 byte), "CJ_TIME" DATE, "EXEUSER" 
    VARCHAR2(50 byte), "EXE_TIME" DATE, "STATUS" NUMBER(1), 
    "REMARK" VARCHAR2(1000 byte),
    CONSTRAINT "PK_CHECKTASK" PRIMARY KEY("ID") 
    USING INDEX  
);
CREATE TABLE "DJ_CZ" ("XH" NUMBER(12) NOT NULL, "QYNM" 
    NUMBER(20) DEFAULT 0 NOT NULL, "DZDAH" NUMBER(20) DEFAULT 0 
    NOT NULL, "SWDJZH" VARCHAR2(20 byte) NOT NULL, "MC" 
    VARCHAR2(100 byte), "DZ" VARCHAR2(100 byte), "FDDBR" 
    VARCHAR2(50 byte), "BGRQ" NUMBER(8), "QYZT" NUMBER(1), 
    "ISMAP" NUMBER(1) NOT NULL, "QYSX" NUMBER(1) NOT NULL, "ZTBM"
    NUMBER(2), "JJXZBM" NUMBER(3), "HYBM" NUMBER(9), "CZFPBM" 
    NUMBER(8), 
    CONSTRAINT "PK_DJ_CZ" PRIMARY KEY("XH") 
    USING INDEX  
);
CREATE TABLE "DJ_DS" ("QYNM" NUMBER(20) NOT NULL, 
    "SWDJZH_DS" VARCHAR2(20 byte) NOT NULL, "MC" VARCHAR2(100 
    byte), "DZ" VARCHAR2(100 byte), "FDDBR" VARCHAR2(50 byte), 
    "DH" VARCHAR2(50 byte), "ZYFW" VARCHAR2(1000 byte), "JYFW" 
    VARCHAR2(1000 byte), "KYRQ" NUMBER(8), "JYFS" VARCHAR2(100 
    byte), "ZCZB" NUMBER(16, 2) DEFAULT 0, "TZZE" NUMBER(16, 2) 
    DEFAULT 0, "ZTBM" NUMBER(2) DEFAULT 0, "DJZLBM" NUMBER(2) 
    DEFAULT 0, "JJXZBM" NUMBER(3) DEFAULT 0, "HYBM" NUMBER(9) 
    DEFAULT 0, "LSGXBM" NUMBER(2) DEFAULT 0, "CZFPBM" NUMBER(8) 
    DEFAULT 0, "NSR_SWJG" NUMBER(11) DEFAULT 0, "ZTBM_S" 
    NUMBER(5), "DJZLBM_S" NUMBER(5), "JJXZBM_S" NUMBER(6), 
    "HYBM_S" NUMBER(18), "LSGXBM_S" NUMBER(5), "CZFPBM_S" 
    NUMBER(16), 
    CONSTRAINT "PK_DJ_DS" PRIMARY KEY("QYNM") 
    USING INDEX  
);
CREATE TABLE "DJ_GS" ("DZDAH" NUMBER(20) NOT NULL, 
    "SWDJZH_GS" VARCHAR2(20 byte) NOT NULL, "ISMAP" NUMBER(1) 
    DEFAULT 1, "MC" VARCHAR2(100 byte), "DZ" VARCHAR2(100 byte), 
    "FDDBR" VARCHAR2(50 byte), "DH" VARCHAR2(50 byte), "ZYFW" 
    VARCHAR2(1000 byte), "JYFW" VARCHAR2(1000 byte), "KYRQ" 
    NUMBER(8), "JYFS" VARCHAR2(100 byte), "ZCZB" NUMBER(16, 2) 
    DEFAULT 0, "TZZE" NUMBER(16, 2) DEFAULT 0, "ZTBM" NUMBER(2) 
    DEFAULT 0, "DJZLBM" NUMBER(2) DEFAULT 0, "JJXZBM" NUMBER(3) 
    DEFAULT 0, "HYBM" NUMBER(9) DEFAULT 0, "LSGXBM" NUMBER(2) 
    DEFAULT 0, "CZFPBM" NUMBER(16) DEFAULT 0, "NSR_SWJG" 
    NUMBER(11) DEFAULT 0, "ZTBM_S" NUMBER(5), "DJZLBM_S" 
    NUMBER(5), "JJXZBM_S" NUMBER(6), "HYBM_S" NUMBER(18), 
    "LSGXBM_S" NUMBER(5), "CZFPBM_S" NUMBER(16), 
    CONSTRAINT "PK_DJ_GS" PRIMARY KEY("DZDAH") 
    USING INDEX  
);
CREATE TABLE "DJ_HDLR" ("SWDJZH" VARCHAR2(20 byte) NOT 
    NULL, "MC" VARCHAR2(100 byte), "DZ" VARCHAR2(100 byte), 
    "FDDBR" VARCHAR2(50 byte), "DH" VARCHAR2(50 byte), "YZBM" 
    VARCHAR2(6 byte), "BGRQ" NUMBER(8), "HDBJ" NUMBER(1) DEFAULT 
    0, "ISMZ" NUMBER(1) DEFAULT 0, "ISGT" NUMBER(1) DEFAULT 0, 
    "ISNEW" NUMBER(1) DEFAULT 0, "ISSWBG" NUMBER(1) DEFAULT 0, 
    "ISMAP" NUMBER(1) DEFAULT 0, "DRRQ" NUMBER(8), "HDRQ" 
    NUMBER(8), "ISYSK" NUMBER(1) DEFAULT 0, "ZTBM" VARCHAR2(2 
    byte) DEFAULT '0', "DJZLBM" VARCHAR2(2 byte) DEFAULT '0', 
    "JJXZBM" VARCHAR2(3 byte) DEFAULT '0', "HYBM" VARCHAR2(6 
    byte) DEFAULT '0', "CYBM" VARCHAR2(1 byte), "LSGXBM" 
    VARCHAR2(2 byte) DEFAULT '0', "CZFPBM" VARCHAR2(8 byte) 
    DEFAULT '0', 
    CONSTRAINT "P_HDLR_SWDJZH" PRIMARY KEY("SWDJZH") 
    USING INDEX  
);
CREATE TABLE "EN_DICTIONARY" ("TNAME" VARCHAR2(30 byte) NOT 
    NULL, "FIELD" VARCHAR2(30 byte) NOT NULL, "MC" VARCHAR2(50 
    byte) NOT NULL, "F_TYPE" NUMBER(1) DEFAULT 0, "VAL_SRC" 
    NUMBER(1) DEFAULT 0, "MAPBM" VARCHAR2(20 byte) DEFAULT '', 
    "SHOWMOD" NUMBER(1) DEFAULT 1, "ISRTK" NUMBER(1) DEFAULT 0, 
    "SORT" NUMBER(3) DEFAULT 0, 
    CONSTRAINT "PK_EN_DIC" PRIMARY KEY("TNAME", "FIELD") 
    USING INDEX  
);
CREATE TABLE "EXCELMAP" ("TID" NUMBER(8) NOT NULL,
    "TDESC" VARCHAR2(100 byte) NOT NULL, "TBNAME" VARCHAR2(40
    byte) NOT NULL, "EXCELCOLINDEX" NUMBER(3) NOT NULL, "COLNAME"
    VARCHAR2(40 byte) NOT NULL,
    CONSTRAINT "PK_EXCEL_MAP" PRIMARY KEY("TID", "TBNAME", "EXCELCOLINDEX")
    USING INDEX
);
CREATE TABLE "EXCELTABLES" ("TBNAME" VARCHAR2(40 byte)
    NOT NULL, "TBDESC" VARCHAR2(100 byte) NOT NULL, "TBOWNER"
    VARCHAR2(42 byte), "SHOWPARM" NUMBER(1) DEFAULT 0, "TID"
    NUMBER(8) NOT NULL,
    CONSTRAINT "PK_EXCELTB" PRIMARY KEY("TBNAME")
    USING INDEX
);
CREATE TABLE "EXCELTB_COLUMNS" ("TBNAME" VARCHAR2(40
    byte) NOT NULL, "COLNAME" VARCHAR2(40 byte) NOT NULL,
    "COLDESC" VARCHAR2(100 byte) NOT NULL, "COLTYPE" NUMBER(1)
    NOT NULL, "SHOWORDER" NUMBER(3), "RPTKEY" NUMBER(1) DEFAULT 0,
    "ISRINDEX" NUMBER(1) DEFAULT 0,
    CONSTRAINT "PK_EXCELCOLS" PRIMARY KEY("TBNAME",
    "COLNAME")
    USING INDEX
);
CREATE TABLE "HD_LOGS" ("LID" NUMBER(18) NOT NULL,
    "CUSER" VARCHAR2(20 byte) NOT NULL,
    "DOTIME" DATE NOT NULL,"IP" varchar2(30 byte), "REMARK" VARCHAR2(500 byte) NOT NULL,
    CONSTRAINT "P_HD_LOGS" PRIMARY KEY("LID")
    USING INDEX
);
CREATE TABLE "JK" ("SKGKDM" NUMBER(10) NOT NULL, 
    "MC" VARCHAR2(100 byte) NOT NULL, 
    CONSTRAINT "PK_JK_INFO" PRIMARY KEY("SKGKDM")
    USING INDEX
); 
CREATE TABLE "MATCH_ENTERPRISE" ("S_ID" VARCHAR2(60 byte), 
    "XH" NUMBER(8), "QYMC" VARCHAR2(100 byte), "SWDJZH" 
    VARCHAR2(30 byte)
);  
CREATE TABLE "MATCH_EXCEL_ENS" ("S_ID" VARCHAR2(60 byte),
    "XH" NUMBER(8), "MC" VARCHAR2(100 byte), "SWDJZH"
    VARCHAR2(30 byte)
);
CREATE TABLE "MATCH_EXCEL_TYPE" ("S_ID" VARCHAR2(60 byte),
    "ENTYPE" VARCHAR2(16 byte), "MATCH_TYPE" VARCHAR2(6 byte)
);
CREATE TABLE "MODULES" ("MODULEID" VARCHAR2(10 byte) NOT 
    NULL, "NAME" VARCHAR2(100 byte) NOT NULL, "PID" VARCHAR2(10 
    byte) DEFAULT '', "HREF" VARCHAR2(100 byte), "TARGET" 
    VARCHAR2(20 byte) DEFAULT '', "QYBJ" NUMBER(1) DEFAULT 1, 
    "ISLEAF" NUMBER(1) NOT NULL, "DORDER" NUMBER(2), 
    CONSTRAINT "PK_MODULE_FT" PRIMARY KEY("MODULEID") 
    USING INDEX  
);
CREATE TABLE "POST" ("POSTID" NUMBER(6) NOT NULL, "POSTNAME"
    VARCHAR2(100 byte) NOT NULL, "REMARK" VARCHAR2(400 byte), 
    CONSTRAINT "PK_POST" PRIMARY KEY("POSTID") 
    USING INDEX  
);
CREATE TABLE "POST_MODULE" ("POSTID" NUMBER(6) NOT NULL, 
    "MODULEID" VARCHAR2(10 byte) NOT NULL, 
    CONSTRAINT "PK_POST_MODULE" PRIMARY KEY("POSTID", "MODULEID")
    USING INDEX  
);
CREATE TABLE "QYFCXX" ("RULEID" NUMBER(18) NOT NULL,
	"QYNM" NUMBER(30) NOT NULL,"DZDAH" NUMBER(30) NOT NULL,
    "SWDJZH" VARCHAR2(20 byte) NOT NULL, "CZFPBM" VARCHAR2(8 
    byte) NOT NULL, "SZBM" VARCHAR2(3 byte) DEFAULT '0' NOT NULL,
    "SEBL" NUMBER(5, 2), 
    CONSTRAINT "P_QYFCXX_KEY" PRIMARY KEY("RULEID","QYNM","DZDAH", 
    "CZFPBM", "SZBM") 
    USING INDEX  
);
CREATE TABLE "QYJH_DETAIL" ("JHID" VARCHAR2(50) NOT NULL,
	"EID" VARCHAR2(20 byte) NOT NULL,"QYBJ" NUMBER(1) DEFAULT 1,
    "SHOWORDER" NUMBER(4) DEFAULT 0,
    CONSTRAINT "PK_QYJH_DETAIL" PRIMARY KEY("JHID", "EID")
    USING INDEX
);
CREATE TABLE "QYJH" ("ID" VARCHAR2(50 byte) NOT NULL,
    "PID" VARCHAR2(20), "NAME" VARCHAR2(100 byte) NOT NULL,
    "ISLEAF" NUMBER(1), "CREATOR" VARCHAR2(42 byte) NOT NULL,
    "ISPRIVATE" NUMBER(1) DEFAULT 0, "CREATETIME" DATE,
    "REMARK" VARCHAR2(2000 byte),
    CONSTRAINT "PK_QYJH" PRIMARY KEY("ID")
    USING INDEX
);
CREATE TABLE "RTK" (
	"KEY" NUMBER(30) NOT NULL, "QY_ID" NUMBER(20) NOT NULL,
	"TAX_ID" NUMBER(20) NOT NULL,"SWDJZH" VARCHAR2(20 byte) NOT NULL,
	"RKRQ" NUMBER(8) NOT NULL, "RTKBJ" NUMBER(1) NOT NULL,
	"SE" NUMBER(16, 2) NOT NULL, "WDLY" NUMBER(1) NOT NULL,
    "JKBM" NUMBER(8), "SZBM" NUMBER(3) NOT NULL,
    "RTKSXBM" NUMBER(2) NOT NULL, "CZFPBM" NUMBER(8) NOT NULL,
    "YSKMBM" NUMBER(10) NOT NULL, "YSJCBM" NUMBER(3) NOT NULL,
    "HYBM" NUMBER(9)NOT NULL, "SWBMBM" NUMBER(8),
    "FCBJ" NUMBER(1) DEFAULT 0 NOT NULL,"SPH" NUMBER(15),
    "SZBM_S" NUMBER(8), "RTKSXBM_S" NUMBER(8),
    "CZFPBM_S" NUMBER(8), "YSJCBM_S" NUMBER(8),
    "HYBM_S" NUMBER(8), "JJXZBM_S" NUMBER(8),
    "LSGXBM_S" NUMBER(8), "SKSRLXBM_DS" NUMBER(8) DEFAULT '0',
    "CZFPBM_ZG" NUMBER(8),
    CONSTRAINT "P_RTK_KEY" PRIMARY KEY("KEY")
    USING INDEX
);
CREATE TABLE "RTK_HDLR" ("KEY" NUMBER(20) NOT NULL,
    "SWDJZH" VARCHAR2(20 byte) NOT NULL, "RKRQ" NUMBER(8) NOT 
    NULL, "RTKBJ" NUMBER(2) DEFAULT 0 NOT NULL, "SE" NUMBER(16, 
    2) DEFAULT 0 NOT NULL, "SPH" VARCHAR2(15 byte), "WDLY" 
    NUMBER(1) DEFAULT 2, "KJYD" NUMBER(6), "JKBM" VARCHAR2(8 
    byte) DEFAULT '0', "SZBM" VARCHAR2(10 byte) DEFAULT '0' NOT 
    NULL, "RTKSXBM" VARCHAR2(2 byte) DEFAULT '0' NOT NULL, 
    "YSKMBM" VARCHAR2(10 byte) DEFAULT '0' NOT NULL, "YSJCBM" 
    VARCHAR2(10 byte) DEFAULT '0' NOT NULL, "CZFPBM" VARCHAR2(10 
    byte) DEFAULT '0' NOT NULL, "QYNM" VARCHAR2(20 byte) DEFAULT 
    '0', "SWBMBM" VARCHAR2(8 byte) DEFAULT '0', "USERID" 
    NVARCHAR2(50) DEFAULT '0', "XH" VARCHAR2(2 byte) DEFAULT '1' 
    NOT NULL, "LRLX" VARCHAR2(2 byte), "REMARK" VARCHAR2(1000 byte),
    CONSTRAINT "P_RTK_HDLR" PRIMARY KEY("KEY")
    USING INDEX
); 
    
CREATE TABLE "RTK_HDLR_IMP" ( "USERID" VARCHAR2(50),
    "SWDJZH" VARCHAR2(20 byte), "SE" NUMBER(16, 2) DEFAULT 0 ,
    "SZBM" VARCHAR2(100 byte),
    "YSKMBM" VARCHAR2(100 byte), "YSJCBM" VARCHAR2(100 byte),
    "CZFPBM" VARCHAR2(100 byte) DEFAULT '0' NOT NULL,
    "XH" NUMBER(2) DEFAULT 1
);
CREATE TABLE "RTK_QYFC" ("KEY" VARCHAR2(100 byte) NOT NULL, 
    "XH" VARCHAR2(2 byte) NOT NULL, "SWDJZH" VARCHAR2(20 byte) 
    NOT NULL, "RKRQ" NUMBER(8) NOT NULL, "RTKBJ" NUMBER(2) 
    DEFAULT 0 NOT NULL, "SE" NUMBER(16, 2) DEFAULT 0 NOT NULL, 
    "SPH" VARCHAR2(15 byte), "WDLY" NUMBER(1) DEFAULT 0, "KJYD" 
    NUMBER(6), "JKBM" VARCHAR2(8 byte) DEFAULT '0', "SZBM" 
    VARCHAR2(3 byte) DEFAULT '0' NOT NULL, "RTKSXBM" VARCHAR2(2 
    byte) DEFAULT '0' NOT NULL, "YSKMBM" VARCHAR2(10 byte) 
    DEFAULT '0' NOT NULL, "YSJCBM" VARCHAR2(3 byte) DEFAULT '0' 
    NOT NULL, "CZFPBM" VARCHAR2(8 byte) DEFAULT '0' NOT NULL, 
    "QYNM" VARCHAR2(20 byte) DEFAULT '0', "SWBMBM" VARCHAR2(8 
    byte) DEFAULT '0', "SEBL" NUMBER(16, 2) DEFAULT 0 NOT NULL, 
    CONSTRAINT "P_RTK_QYFC_KEY" PRIMARY KEY("KEY", "XH") 
    USING INDEX  
);
CREATE TABLE "RULES" ("RULEID" NUMBER(18) NOT NULL, 
    "RULETYPE" NUMBER(1) DEFAULT 0 NOT NULL, "QYBJ" NUMBER(1) 
    DEFAULT 0 NOT NULL, "DETAILTB" VARCHAR2(20 byte) NOT NULL, 
    "OBJAFFECT" VARCHAR2(50 byte) DEFAULT '', "BEGINDATE" 
    NUMBER(8), "ENDDATE" NUMBER(8), 
    CONSTRAINT "PK_RULES" PRIMARY KEY("RULEID") 
    USING INDEX  
);

CREATE TABLE "RULESOFBASE" ("RULEID" NUMBER(18) NOT NULL, 
    "SWDJZH" VARCHAR2(20 byte) NOT NULL, "EXCYEAR" NUMBER(4) NOT 
    NULL, "STATUS" NUMBER(1) DEFAULT 0, 
    CONSTRAINT "PK_RULESOFBASE" PRIMARY KEY("RULEID") 
    USING INDEX  
);

CREATE TABLE "SYSTEMSET" ("ITEM" VARCHAR2(50 byte) NOT NULL,
    "INAME" VARCHAR2(100 byte) NOT NULL, "IVALUE" VARCHAR2(50 byte) NOT NULL,
    "REMARK" VARCHAR2(1000 BYTE),
    CONSTRAINT "P_SYSTEMSET" PRIMARY KEY("ITEM")
    USING INDEX
);
CREATE TABLE "USERS" (
	"USERID" VARCHAR2(50 byte) NOT NULL, 
    "NAME" VARCHAR2(200 byte) NOT NULL, "USERDESC" VARCHAR2(1000 byte), 
    "PASSWORD" VARCHAR2(20 byte) DEFAULT '', 
    "ISMANAGER" NUMBER(1) DEFAULT 0 NOT NULL, "FJBM" VARCHAR2(10 byte) DEFAULT '', 
    "KHRQ" VARCHAR2(8 byte), "QYBJ" NUMBER(1) DEFAULT 1, 
    CONSTRAINT "PK_USERS" PRIMARY KEY("USERID") 
    USING INDEX  
);
CREATE TABLE "USER_POST" ("USERID" VARCHAR2(42 byte) NOT 
    NULL, "POSTID" NUMBER(6) NOT NULL, 
    CONSTRAINT "PK_USER_POST" PRIMARY KEY("USERID", "POSTID") 
    USING INDEX  
);
CREATE TABLE "USER_XZ" ("USERID" VARCHAR2(50 byte) NOT 
    NULL, "CZFPBM" VARCHAR2(42 byte) NOT NULL, 
    CONSTRAINT "PK_USERS_XZ" PRIMARY KEY("USERID", "CZFPBM") 
    USING INDEX  
);

CREATE TABLE "YSSR" (
	"SKGKDM_JK" NUMBER(10) NOT NULL, "MDGKDM_JK" NUMBER(10),
	"SSGKDM_JK" NUMBER(10), "YSJC_JK" NUMBER(2) NOT NULL,
	"JGDM_JK" NUMBER(20) NOT NULL, "KMDM_JK" NUMBER(10) NOT NULL,
	"KMMC_JK" VARCHAR2(50),"ZWRQ_JK" NUMBER(8) NOT NULL,
	"YSZL_JK" NUMBER(1), "RLJ_JK" NUMBER(16,2),
	"YLJ_JK" NUMBER(16, 2), "NLJ_JK" NUMBER(16, 2),
    CONSTRAINT "P_KEY_YSSR" PRIMARY KEY("SKGKDM_JK", "YSJC_JK",
    "JGDM_JK","KMDM_JK","ZWRQ_JK")
    USING INDEX
);
CREATE TABLE "YSSR_TMP" (
	"SKGKDM_JK" NUMBER(10) NOT NULL, "MDGKDM_JK" NUMBER(10),
	"SSGKDM_JK" NUMBER(10), "YSJC_JK" NUMBER(2) NOT NULL,
	"JGDM_JK" NUMBER(20) NOT NULL, "KMDM_JK" NUMBER(10) NOT NULL,
	"KMMC_JK" VARCHAR2(50),"ZWRQ_JK" NUMBER(8) NOT NULL,
	"YSZL_JK" NUMBER(1)NOT NULL, "RLJ_JK" NUMBER(16,2),
	"YLJ_JK" NUMBER(16, 2), "NLJ_JK" NUMBER(16, 2)

);
CREATE TABLE "YSSR_IMP_SET" (
	"ID" NUMBER(18) NOT NULL,"SKGKDM_JK" NUMBER(10) NOT NULL, "MTYPE" NUMBER(1) NOT NULL,
	"FNODE" VARCHAR2(200 byte) NOT NULL, "COLNAME" VARCHAR2(30 byte) NOT NULL,
	"DTYPE" NUMBER(1)DEFAULT 0,"RPTKEYFLAG" NUMBER(1) DEFAULT 0,
    CONSTRAINT "PK_YSSR_IMP_SET" PRIMARY KEY("ID")
    USING INDEX
);
CREATE TABLE "YSSR_LOG" (
	"SKGKDM_JK" NUMBER(10) NOT NULL,"ZWRQ_JK" NUMBER(8) NOT NULL,
	"ZWRQ_YEAR" NUMBER(4), "ZWRQ_MON" NUMBER(2),
	"ZWRQ_DAY" NUMBER(2), "USERID" VARCHAR2(50) NOT NULL,
	"CZRQ" NUMBER(8),
    CONSTRAINT "PK_YSSR_LOG" PRIMARY KEY("SKGKDM_JK","ZWRQ_JK")
    USING INDEX
);
--sequence

CREATE SEQUENCE "SQ_CHECKTASK" INCREMENT BY 1 START WITH 1 
    MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;
CREATE SEQUENCE "SQ_DJ_CZ" INCREMENT BY 1 START WITH 30324 
    MAXVALUE 1.0E28 MINVALUE 30264 NOCYCLE 
    CACHE 20 NOORDER;
CREATE SEQUENCE "SQ_HD_LOGS" INCREMENT BY 1 START WITH 1 
    MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;
CREATE SEQUENCE "SQ_POST" INCREMENT BY 1 START WITH 1 
    MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;
CREATE SEQUENCE "SQ_RTK_HDLR" INCREMENT BY 1 START WITH 1 
    MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;
CREATE SEQUENCE "SQ_RULEOFBASE" INCREMENT BY 1 START WITH 1
    MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE
    CACHE 20 NOORDER;
CREATE SEQUENCE "SQ_RULES" INCREMENT BY 1 START WITH 1
    MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE
    CACHE 20 NOORDER;

